# Generated by Django 5.0.14 on 2025-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholdersHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shareholder_id', models.BigIntegerField()),
                ('shareholder_shares', models.BigIntegerField()),
                ('shareholder_percentage', models.FloatField()),
                ('shareholder_instrument_id', models.CharField(max_length=50)),
                ('shareholder_name', models.CharField(max_length=255)),
                ('change', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ShareholdersHistory',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
